"""
Django settings for bs_angel_admin project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

#将apps路径加入到python搜索路径
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#mb@j9r8&g!1#!9wskx#%e#^ty582pmib^isn9+^4qq0ih*ltx'

# qiniu KEY
QINIU_ACCESS_KEY = 'BcM4U6mciW4jUpbkc_UNl4-QjMLs24m7_-rhIYEu'
QINIU_SECRET_KEY = 'JKlgYOmQ7_HgiCpPnDUEYTK5TBAD898bBum0O_9s'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_swagger',
    'corsheaders',
    'django_apscheduler',
    'login',
    'system',
    'worker',
) 

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'apps.cmw_user.utils.middleware.UserAuthMiddle',
    'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 跨域增加忽略
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = (
    '*'
)
CORS_ALLOW_METHODS = (
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'token',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'X-File-Name',
    'X-File-Type',
    'X-File-Size',
)
#部署到云服务上必备
ALLOWED_HOSTS = ['*']

ROOT_URLCONF = 'bs_angel_admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bs_angel_admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'bs_angel',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',                      # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '3306',              
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

LOCAL_URL = 'http://127.0.0.1:7080'
AVATAR = "http://f.hiphotos.baidu.com/image/pic/item/8601a18b87d6277ffbd3a0d722381f30e824fc18.jpg"
OAUTH_GITHUB_CONFIG = {
    'oauth_type_id' : 3,   #对应模型中记录的ID
    'oauth_type' : 'Github',
 
    'client_id' : '35ba11253702082d5081', 
    'client_secret' : 'da3e790dab6a3594548a72928af26dfe9215197c',
    'redirect_uri' : 'http://127.0.0.1:7080/user/github_check',#回调地址
    'scope' : 'user:email', #授权的权限
    'state' : 'Github',
 
    #其他请求的链接
    'url_authorize' : 'https://github.com/login/oauth/authorize',
    'url_access_token' : 'https://github.com/login/oauth/access_token',
    'url_open_id' : '',
    'url_user_info' : 'https://api.github.com/user',
    'url_email' : 'https://api.github.com/user/emails',
}
