# Generated by Django 2.0.2 on 2019-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_schoolinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposer', models.CharField(max_length=64, null=True, unique=True, verbose_name='创建人u_id')),
                ('proposer_name', models.CharField(max_length=64, null=True, verbose_name='创建人姓名')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='宿舍地址')),
                ('floor', models.CharField(max_length=100, null=True, verbose_name='宿舍楼层')),
                ('dorm_id', models.CharField(max_length=100, null=True, verbose_name='宿舍号')),
                ('status', models.IntegerField(default=0, verbose_name='宿舍状态')),
                ('residents', models.CharField(default='无', max_length=200, null=True, verbose_name='住户信息')),
                ('remark', models.CharField(max_length=500, null=True, verbose_name='备注信息')),
                ('in_date', models.CharField(max_length=200, null=True, verbose_name='入住时间')),
            ],
            options={
                'db_table': 'dorm_info',
            },
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
