# Generated by Django 2.0.2 on 2019-05-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190508_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorminfo',
            old_name='proposer',
            new_name='u_id',
        ),
    ]
