# Generated by Django 2.0.2 on 2019-05-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190508_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorminfo',
            name='dorm_size',
            field=models.IntegerField(default=6, verbose_name='宿舍大小'),
        ),
    ]
