# Generated by Django 2.0.2 on 2019-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_dorminfo_dorm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminfo',
            name='u_id',
            field=models.CharField(max_length=64, null=True, verbose_name='创建人u_id'),
        ),
    ]
