# Generated by Django 2.0.2 on 2019-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20190508_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorminfo',
            name='dorm_type',
            field=models.CharField(max_length=200, null=True, verbose_name='宿舍类型'),
        ),
    ]
