# Generated by Django 2.0.2 on 2019-05-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_dorminfo_dorm_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminfo',
            name='dorm_type',
            field=models.CharField(default='男', max_length=200, null=True, verbose_name='宿舍类型'),
        ),
    ]
