# Generated by Django 2.0.2 on 2019-05-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20190510_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorminfo',
            name='residents',
            field=models.CharField(default='无', max_length=2000, null=True, verbose_name='住户信息'),
        ),
    ]
