# Generated by Django 2.0.2 on 2019-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_order',
            name='school',
            field=models.CharField(max_length=64, null=True, verbose_name='分配单位'),
        ),
    ]
