# Generated by Django 2.0.2 on 2019-05-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_work_order_kemans_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='step_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='当前步骤'),
        ),
    ]
