# Generated by Django 2.0.2 on 2019-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_auto_20190505_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(default=1, verbose_name='工单状态')),
                ('school', models.CharField(max_length=64, null=True, verbose_name='所在单位')),
                ('step', models.IntegerField(blank=True, default=0, null=True, verbose_name='当前步骤')),
                ('proposer', models.CharField(max_length=64, null=True, verbose_name='申请人ID')),
                ('proposer_name', models.CharField(max_length=64, null=True, verbose_name='申请人姓名')),
                ('professional', models.CharField(max_length=64, null=True, verbose_name='申请人职业')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('create_date', models.CharField(max_length=100, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限申请流程工單',
                'db_table': 'auth_work',
            },
        ),
    ]
