# Generated by Django 2.0.2 on 2019-05-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_auth_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_work',
            name='proposer',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='申请人ID'),
        ),
    ]
