# Generated by Django 2.0.2 on 2019-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_auto_20190506_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_work',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='auth_work',
            name='step',
            field=models.IntegerField(default=0, null=True, verbose_name='当前步骤'),
        ),
    ]
