# Generated by Django 2.0.2 on 2019-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_auto_20190509_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_work',
            name='proposer',
            field=models.CharField(max_length=64, null=True, verbose_name='申请人ID'),
        ),
    ]
