# Generated by Django 2.0.2 on 2019-05-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='宿舍分配状态（（0待分配,1分配中,2 已分配））'),
        ),
    ]
